spring:
  application:
    name: bank-account
  jackson:
    serialization:
      write-dates-as-timestamps: false
server:
  port: ${SERVER_PORT:8080}
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.yourorg: DEBUG

bank:
  kafka:
    topics:
      operations: bank.operations
      accounts: bank.accounts